"""Config files for tools that only read files: recyclarr + decluttarr."""
import os
import subprocess

import yaml

from ..common import CONFIG, LOCAL, STACK, Ctx, Log, chown, write_if_changed

RECYCLARR = CONFIG / "recyclarr"


def recyclarr(ctx: Ctx):
    Log.section("recyclarr (TRaSH quality profiles)")
    if not {"sonarr", "radarr"} & ctx.keys.keys():
        return
    secrets = {f"{app}_api_key": ctx.keys[app] for app in ("sonarr", "radarr") if app in ctx.keys}
    write_if_changed(ctx, RECYCLARR / "secrets.yml", yaml.safe_dump(secrets), "recyclarr secrets.yml")
    config = LOCAL / "recyclarr.yml" if (LOCAL / "recyclarr.yml").is_file() else STACK / "recyclarr.yml"
    cmd = ["recyclarr", "sync", "--config", str(config)]
    if ctx.dry_run:
        cmd.append("--preview")
    Log.info(f"running: {' '.join(cmd)}")
    r = subprocess.run(cmd, capture_output=True, text=True,
                       env=os.environ | {"RECYCLARR_CONFIG_DIR": str(RECYCLARR)})
    for line in (r.stdout + r.stderr).splitlines()[-25:]:
        Log.info(f"  {line}")
    if r.returncode != 0:
        Log.warn(f"recyclarr sync exited with {r.returncode}")
    for p in RECYCLARR.rglob("*"):
        chown(p)


def decluttarr(ctx: Ctx):
    Log.section("decluttarr")
    cfg = ctx.cfg.get("decluttarr") or {}
    doc = {
        "general": cfg.get("general", {}),
        "jobs": cfg.get("jobs", {}),
        "instances": {app: [{"base_url": f"http://{app}:{port}", "api_key": ctx.keys[app]}]
                      for app, port in (("sonarr", 8989), ("radarr", 7878)) if app in ctx.keys},
        "download_clients": {"qbittorrent": [{
            "base_url": "http://gluetun:8080", "username": ctx.user, "password": ctx.password,
            "name": "qBittorrent",
        }]},
    }
    text = "# Generated by stack-init from stack/stack.yml — edit that instead.\n" + \
        yaml.safe_dump(doc, sort_keys=False)
    if write_if_changed(ctx, CONFIG / "decluttarr" / "config.yaml", text, "decluttarr config.yaml"):
        Log.info("if decluttarr is already running: `docker compose restart decluttarr`")
